[package]
version = "0.4.0"
name = "halfin"
description = "A {regtest} bitcoin node runner 🏃‍♂️"
authors = ["Luis Schwab <dev@luisschwab.net"]
repository = "https://github.com/luisschwab/halfin"
documentation = "https://docs.rs/halfin"
keywords = ["bitcoin", "runner", "testing"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.85.0" # MSRV

[features]
default = ["bitcoind", "utreexod"]
bitcoind = []
utreexod = []
electrs = ["bitcoind", "dep:electrum-client"]

[dependencies]
corepc-client = { version = "=0.16.0", features = ["client-sync"] }
electrum-client = { version = "=0.25.0", default-features = false, optional = true }
tempfile = { version = "=3.27.0", default-features = false }
serde_json = { version = "=1.0.150", default-features = false }
tracing = { version = "=0.1.44", default-features = false, features = ["std"] }
which = { version = "=8.0.4", default-features = false }

[build-dependencies]
anyhow = { version = "=1.0.102" }
bitcoin_hashes = { version = "=0.20.0", features = ["hex"] }
flate2 = { version = "=1.1.9" }
bitreq = { version = "=0.3.7", features = ["https"] }
tar = { version = "=0.4.46" }
zip = { version = "=7.2.0", default-features = false, features = ["bzip2", "deflate"] }

[dev-dependencies]
tracing-subscriber = { version = "=0.3.23", features = ["fmt"] }
lazy_static = { version = "=1.5.0" } # blame: tracing-subsbcriber
xshell = { version = "=0.3.0-pre.2" }

[[example]]
name = "cross-compile-electrs"
path = "contrib/compile_electrs/build.rs"
test = false
bench = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.rbmt.toolchains]
stable = "1.96.0"
nightly = "nightly-2026-06-23"

[package.metadata.rbmt.test]
sample_strategy = "all"

# Allow packages of different versions in the dependency tree.
[package.metadata.rbmt.lint]
allowed_duplicates = [
    "base64",
]

[lints.clippy]
let-and-return = "allow"
