// SPDX-License-Identifier: MIT OR Apache-2.0

//! Start and control a `btcd` process.
//!
//! [`BtcD`] starts `btcd` on the regtest network.
//! It gives access to the JSON-RPC client, process data, and test operations.
//!
//! ## Start a [`Node`]
//!
//! ```rust
//! use halfin::node::btcd::BtcD;
//!
//! // Start a node with the default configuration.
//! let node = BtcD::new().unwrap();
//! ```
//!
//! By default, each [`BtcD`] instance uses a temporary directory.
//! [`Drop`] removes this directory.
//! Set [`BtcDConf::staticdir`] to keep the data after the process stops.
//!
//! [`Node`]: crate::node::Node

use core::net::SocketAddr;
use core::net::SocketAddrV4;
use std::fs;
use std::path::Path;
use std::path::PathBuf;
use std::process::Child;
use std::process::Command;
use std::process::ExitStatus;
use std::process::Stdio;
use std::str::FromStr;
use std::thread::sleep;
use std::time::Duration;
use std::time::Instant;

use corepc_client::bitcoin::Address;
use corepc_client::bitcoin::BlockHash;
use corepc_client::bitcoin::Network;
use corepc_client::bitcoin::address::NetworkUnchecked;
use corepc_client::client_sync::Auth;
use corepc_client::client_sync::v17::AddNodeCommand;
use corepc_client::client_sync::v17::Client;
use tracing::debug;

use crate::CONNECTION_INTERVAL;
use crate::CONNECTION_TIMEOUT;
use crate::DataDir;
use crate::Error;
use crate::IPV4_LOCALHOST;
use crate::SPAWN_ATTEMPTS;
use crate::SPAWN_INTERVAL;
use crate::STARTUP_TIMEOUT;
use crate::find_conflicting_argument;
use crate::get_available_port;
use crate::init_data_dir;
use crate::node::Node;
use crate::node::NodeArgs;
use crate::node::NodeError;
use crate::node::PruneMode;
use crate::node::RPC_PASS;
use crate::node::RPC_USER;
use crate::node::validate_node_arguments;
use crate::node::write_rpc_cookie;
use crate::pipe_to_tracing;

/// Bundled `btcd` version metadata.
mod versions;

/// Default regtest address used for blocks generated by `btcd`.
const DEFAULT_MINING_ADDRESS: &str = "bcrt1qusgerygumpd0ztn735s5pypq6wsv2zzhuc4yak";

/// Minimum automatic pruning target supported by `btcd`, in MiB.
const MIN_PRUNE_TARGET_MIB: u64 = 1_536;

/// Return the path to the downloaded `btcd` binary.
///
/// At compile time, `build.rs` downloads and extracts the binary.
/// It stores the binary path in `HALFIN_BTCD_PATH`.
///
/// # Errors
///
/// Returns [`Error::BinaryNotFound`] if the compiled-in binary path does not exist.
pub fn get_btcd_path() -> Result<PathBuf, Error> {
    #[allow(unused_mut)]
    let mut bin_path = PathBuf::from(option_env!("HALFIN_BTCD_PATH").unwrap_or(""));

    // Add the `.exe` suffix on Windows
    #[cfg(target_os = "windows")]
    if bin_path.extension().is_none() {
        bin_path.set_extension("exe");
    }

    let bin_name = BtcD::get_bin_name().to_string();
    match bin_path.exists() {
        true => Ok(bin_path),
        false => Err(Error::BinaryNotFound((bin_name, bin_path))),
    }
}

/// Arguments specific to `btcd`.
#[derive(Debug, PartialEq, Eq, Clone)]
pub struct BtcDArgs {
    /// Enables peer discovery through DNS seeds.
    pub dns_seed: bool,
    /// Address used as the coinbase output when generating blocks.
    pub mining_address: Option<Address<NetworkUnchecked>>,
}

/// Configuration for a [`BtcD`] instance.
///
/// # Directory precedence
///
/// Set only `tmpdir` or `staticdir`.
/// If you set both fields, the function returns [`Error::BothDirectoriesSpecified`].
///
/// | `tmpdir` | `staticdir` | Result |
/// |----------|-------------|--------|
/// | `None`   | `None`      | System temporary directory (deleted at `Drop`) |
/// | `Some`   | `None`      | Custom temporary root (deleted at `Drop`) |
/// | `None`   | `Some`      | Persistent directory (kept at `Drop`) |
/// | `Some`   | `Some`      | **Error** |
#[derive(Debug, PartialEq, Eq, Clone)]
pub struct BtcDConf {
    /// Arguments shared with other [`Node`] implementations.
    pub args: NodeArgs,

    /// Arguments specific to `btcd`.
    pub btcd_args: BtcDArgs,

    /// Extra CLI arguments sent unchanged to the `btcd` process.
    ///
    /// Do not use raw arguments for options in [`args`](Self::args) or
    /// [`btcd_args`](Self::btcd_args). Do not duplicate an option that `halfin` controls.
    /// A duplicate option returns [`NodeError::ConflictingArgument`].
    pub raw_args: Vec<String>,

    /// Root for the new temporary directory of each instance.
    /// If this field is empty, the function uses `TEMPDIR_ROOT`.
    /// If `TEMPDIR_ROOT` is empty, the function uses the system temporary directory.
    pub tmpdir: Option<PathBuf>,

    /// Persistent data directory.
    /// The function creates the directory if necessary.
    /// [`Drop`] stops the process and keeps the files.
    pub staticdir: Option<PathBuf>,

    /// Maximum number of attempts to start `btcd`.
    ///
    /// Each attempt uses new random ports. Thus, a new attempt can correct a temporary port
    /// conflict. The default value is [`SPAWN_ATTEMPTS`].
    pub max_retries: u8,
}

impl Default for BtcDConf {
    fn default() -> Self {
        Self {
            args: NodeArgs {
                network: Network::Regtest,
                fixed_peers: Vec::new(),
                cbf_index: true,
                prune: PruneMode::Disabled,
                v2_transport: true,
                txindex: true,
            },
            btcd_args: BtcDArgs {
                dns_seed: false,
                mining_address: Some(
                    Address::from_str(DEFAULT_MINING_ADDRESS)
                        .expect("the built-in mining address must be valid"),
                ),
            },
            raw_args: Vec::new(),
            tmpdir: None,
            staticdir: None,
            max_retries: SPAWN_ATTEMPTS,
        }
    }
}

impl AsRef<NodeArgs> for BtcDConf {
    fn as_ref(&self) -> &NodeArgs {
        &self.args
    }
}

/// A running `btcd` [`Node`].
///
/// [`BtcD::from_bin`] and related functions start the [`Node`].
/// [`Drop`] stops the [`Node`] and deletes its temporary files.
///
/// # Authentication
///
/// RPC authentication uses a `.cookie` file that `halfin` creates in the runtime data directory.
/// The same file authenticates the `halfin` client and each [`Indexer`](crate::indexer::Indexer).
///
/// # Networking
///
/// At startup, the operating system selects temporary RPC and P2P ports.
/// Use [`BtcD::get_rpc_socket`] and [`BtcD::get_p2p_socket`] to get these ports.
#[derive(Debug)]
pub struct BtcD {
    /// Handle for the `btcd` child process.
    process: Child,

    /// Authenticated JSON-RPC client connected to the [`Node`].
    pub client: Client,

    /// Data directory of the [`Node`] and its cleanup state.
    working_directory: DataDir,

    /// Complete configuration used to start the [`Node`].
    config: BtcDConf,

    /// Address of the JSON-RPC server.
    rpc_socket: SocketAddr,

    /// Address of the P2P listener.
    p2p_socket: SocketAddr,
}

#[rustfmt::skip]
impl Node for BtcD {
    type Config = BtcDConf;

    fn get_name() -> &'static str { versions::BTCD_NAME }

    fn get_bin_name() -> &'static str { versions::BTCD_BIN_NAME }

    fn get_config(&self) -> &BtcDConf { self.get_config() }

    fn get_working_directory(&self) -> PathBuf { self.get_working_directory() }

    fn get_rpc_socket(&self) -> SocketAddr { self.get_rpc_socket() }

    fn generate(&self, count: u32) -> Result<Vec<BlockHash>, Error> { self.generate(count) }

    fn get_p2p_socket(&self) -> SocketAddr { self.get_p2p_socket() }

    fn has_peer(&self, socket: SocketAddr) -> Result<bool, Error> { self.has_peer(socket) }

    fn add_peer(&self, socket: SocketAddr) -> Result<(), Error> { self.add_peer(socket) }

    fn get_peer_count(&self) -> Result<u32, Error> { self.get_peer_count() }

    fn get_chain_tip(&self) -> Result<u32, Error> { self.get_chain_tip() }

    fn get_filter_tip(&self) -> Result<u32, Error> { self.get_filter_tip() }

    fn get_block_hash(&self, height: u32) -> Result<BlockHash, Error> { self.get_block_hash(height) }

    fn call(&self, method: &str, args: &[serde_json::Value]) -> Result<serde_json::Value, Error> {
        Ok(self.client.call(method, args).map_err(NodeError::JsonRpc)?)
    }

}

impl BtcD {
    /// Start [`BtcD`] with the binary from [`get_btcd_path`].
    /// Use the default [`BtcDConf`].
    ///
    /// If the binary is not in `target/bin/`, `build.rs` downloads it from `github.com`.
    ///
    /// # Errors
    ///
    /// Returns an error if the function cannot find the binary or start the [`Node`].
    pub fn new() -> Result<Self, Error> {
        Self::from_bin(get_btcd_path()?)
    }

    /// Start [`BtcD`] with the binary from [`get_btcd_path`].
    /// Use the specified [`BtcDConf`].
    ///
    /// If the binary is not in `target/bin/`, `build.rs` downloads it from `github.com`.
    ///
    /// # Errors
    ///
    /// Returns an error if the function cannot find the binary or start the [`Node`].
    /// Returns an error if the configuration is not valid.
    pub fn new_with_conf(conf: &BtcDConf) -> Result<Self, Error> {
        Self::from_bin_with_conf(get_btcd_path()?, conf)
    }

    /// Start the binary at [`Path`] with the default [`BtcDConf`].
    ///
    /// # Errors
    ///
    /// Returns an error if `btcd_bin` is not valid or the function cannot start the [`Node`].
    pub fn from_bin<P: AsRef<Path>>(btcd_bin: P) -> Result<Self, Error> {
        Self::from_bin_with_conf(btcd_bin, &BtcDConf::default())
    }

    /// Start the binary at [`Path`] with the specified [`BtcDConf`].
    ///
    /// The method uses at most [`BtcDConf::max_retries`] attempts.
    ///
    /// 1. Select new temporary RPC and P2P ports.
    /// 2. Start `btcd` with these ports and a new data directory.
    /// 3. Wait a maximum of 10 seconds for the RPC server to respond.
    ///
    /// # Errors
    ///
    /// Returns an error if the binary path is not valid or the function cannot create the working
    /// directory. Returns an error if RPC setup fails or all start attempts fail.
    #[allow(clippy::too_many_lines)]
    pub fn from_bin_with_conf<P: AsRef<Path>>(btcd_bin: P, conf: &BtcDConf) -> Result<Self, Error> {
        let configured_args = Self::configured_args(conf)?;

        // Validate the `btcd_bin` path.
        let btcd_bin = btcd_bin.as_ref();
        // The path must be absolute.
        if !btcd_bin.is_absolute() {
            return Err(Error::BinaryPathNotAbsolute {
                bin_name: Self::get_bin_name().to_string(),
                path: btcd_bin.display().to_string(),
            });
        }
        // The path must be a file.
        if !btcd_bin.is_file() {
            return Err(Error::BinaryPathNotFile {
                bin_name: Self::get_bin_name().to_string(),
                path: btcd_bin.display().to_string(),
            });
        }

        for _attempt in 0..conf.max_retries {
            let working_directory = init_data_dir(
                conf.tmpdir.as_deref(),
                conf.staticdir.as_deref(),
                "halfin-btcd-",
            )?;
            let cookie_file = write_rpc_cookie(&working_directory.path())?;

            let rpc_port = get_available_port();
            let rpc_socket = SocketAddr::V4(SocketAddrV4::new(IPV4_LOCALHOST, rpc_port));
            let rpc_url = format!("http://{}", rpc_socket);

            let p2p_port = get_available_port();
            let p2p_socket = SocketAddr::V4(SocketAddrV4::new(IPV4_LOCALHOST, p2p_port));

            let datadir_arg = format!("--datadir={}", working_directory.path().display());
            let config_file = working_directory.path().join("btcd.conf");
            fs::write(&config_file, []).map_err(Error::Io)?;
            let configfile_arg = format!("--configfile={}", config_file.display());
            let logdir_arg = format!(
                "--logdir={}",
                working_directory.path().join("logs").display()
            );
            let rpclisten_arg = format!("--rpclisten=127.0.0.1:{}", rpc_port);
            let rpcuser_arg = format!("--rpcuser={RPC_USER}");
            let rpcpass_arg = format!("--rpcpass={RPC_PASS}");
            let listen_arg = format!("--listen=127.0.0.1:{}", p2p_port);
            debug!(
                "Spawning {} [RPC_SOCKET={}, P2P_SOCKET={}, DATADIR={}]",
                Self::get_name(),
                rpc_socket,
                p2p_socket,
                working_directory.path().display()
            );

            let mut process = Command::new(btcd_bin)
                .args(&configured_args)
                .args(&conf.raw_args)
                .arg(&configfile_arg)
                .arg(&datadir_arg)
                .arg(&logdir_arg)
                .arg(&rpclisten_arg)
                .arg(&rpcuser_arg)
                .arg(&rpcpass_arg)
                .arg(&listen_arg)
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
                .map_err(Error::FailedToSpawn)?;

            // Add a small timeout to let `btcd` fail
            // and retry in the case of a port collision.
            sleep(SPAWN_INTERVAL);

            // If the process exited immediately, try again with new ports.
            match process.try_wait() {
                Ok(Some(status)) => {
                    let output = process.wait_with_output().map_err(Error::Io)?;
                    eprintln!(
                        "{} exited immediately with status={status}; stdout={}; stderr={}",
                        Self::get_name(),
                        String::from_utf8_lossy(&output.stdout).trim(),
                        String::from_utf8_lossy(&output.stderr).trim(),
                    );
                    continue;
                }
                Err(err) => {
                    debug!(
                        "{} status check failed, retrying with fresh ports: {}",
                        Self::get_name(),
                        err
                    );
                    let _ = process.kill();
                    let _ = process.wait();
                    continue;
                }
                Ok(None) => {}
            }

            // Pipe the node's stdout/stderr into `tracing` so its logs are
            // visible alongside halfin's own. The reader threads exit on EOF
            // when the process dies.
            if let Some(stdout) = process.stdout.take() {
                pipe_to_tracing(stdout, "btcd");
            }
            if let Some(stderr) = process.stderr.take() {
                pipe_to_tracing(stderr, "btcd");
            }

            let auth = Auth::CookieFile(cookie_file);
            if let Ok(client) = Self::wait_for_client(&rpc_url, &auth, STARTUP_TIMEOUT) {
                sleep(Duration::from_millis(200));

                debug!(
                    "Started {} [PID={}, RPC_SOCKET={}, P2P_SOCKET={}, DATADIR={}]",
                    Self::get_name(),
                    process.id(),
                    rpc_socket,
                    p2p_socket,
                    working_directory.path().display()
                );

                return Ok(Self {
                    process,
                    client,
                    working_directory,
                    config: conf.clone(),
                    rpc_socket,
                    p2p_socket,
                });
            }
            let _ = process.kill();
            let _ = process.wait();
        }

        Err(Error::StartupAttemptsExhausted(conf.max_retries))
    }

    /// Send `stop` via RPC and wait for the process to exit.
    ///
    /// [`Drop`] stops the process without a call to this method.
    /// Call this method to get the exit status or confirm that the process has stopped.
    ///
    /// # Errors
    ///
    /// Returns an error if the RPC stop call fails.
    /// Returns an error if the function cannot wait for the child process.
    pub fn stop(&mut self) -> Result<ExitStatus, Error> {
        debug!("Stopping {} [PID={}]", Self::get_name(), self.process.id());

        // Send a `stop` over RPC.
        let _ = self.client.stop().map_err(NodeError::FailedToStop)?;
        // Wait for the process to terminate and get its exit status.
        let exit_status = self.process.wait().map_err(Error::Io)?;

        Ok(exit_status)
    }

    /// Return the operating system process ID of `btcd`.
    pub fn get_pid(&self) -> u32 {
        let pid = self.process.id();

        debug!("{}: got pid={}", Self::get_name(), pid);

        pid
    }

    /// Return the data directory of [`BtcD`].
    pub fn get_working_directory(&self) -> PathBuf {
        let working_directory = self.working_directory.path();

        debug!(
            "{}: got working directory at path={}",
            Self::get_name(),
            working_directory.display()
        );

        working_directory
    }

    /// Return the complete configuration used to start this [`Node`].
    pub fn get_config(&self) -> &BtcDConf {
        &self.config
    }

    /// Return a reference to the RPC [`Client`] of [`BtcD`].
    pub fn get_rpc_client(&self) -> &Client {
        debug!(
            "{}: got rpc client for socket={}",
            Self::get_name(),
            self.rpc_socket
        );

        &self.client
    }

    /// Return the JSON-RPC [`SocketAddr`] of the [`Node`].
    pub fn get_rpc_socket(&self) -> SocketAddr {
        debug!(
            "{}: got rpc socket at socket={}",
            Self::get_name(),
            self.rpc_socket
        );

        self.rpc_socket
    }

    /// Return the P2P [`SocketAddr`] of the [`Node`].
    ///
    /// Pass this to [`BtcD::add_peer`] on another [`Node`] to connect the two.
    pub fn get_p2p_socket(&self) -> SocketAddr {
        debug!(
            "{}: got p2p socket at socket={}",
            Self::get_name(),
            self.p2p_socket
        );

        self.p2p_socket
    }

    /// Return the current chain height.
    ///
    /// # Errors
    ///
    /// Returns an error if the JSON-RPC call fails or the response does not contain a block height.
    pub fn get_chain_tip(&self) -> Result<u32, Error> {
        let height = self
            .client
            .call::<serde_json::Value>("getblockchaininfo", &[])
            .map_err(NodeError::JsonRpc)?["blocks"]
            .as_u64()
            .ok_or(Error::UnexpectedResponse(
                "getblockchaininfo returned no `blocks` field".to_string(),
            ))? as u32;

        debug!("{}: got chain tip at height={}", Self::get_name(), height);

        Ok(height)
    }

    /// Return the current filter height.
    ///
    /// # Errors
    ///
    /// Returns an error if the chain tip, block hash, or compact-filter RPC call fails.
    pub fn get_filter_tip(&self) -> Result<u32, Error> {
        let height = self.get_chain_tip()?;
        let hash = self.get_block_hash(height)?;

        self.client
            .call::<serde_json::Value>(
                "getcfilterheader",
                &[
                    serde_json::Value::String(hash.to_string()),
                    serde_json::Value::Number(0.into()),
                ],
            )
            .map_err(NodeError::JsonRpc)?;

        debug!("{}: got filter tip at height={}", Self::get_name(), height);

        Ok(height)
    }

    /// Return the [`BlockHash`] of the block at `height`.
    ///
    /// # Errors
    ///
    /// Returns an error if the JSON-RPC call fails or the response is not a valid block hash.
    pub fn get_block_hash(&self, height: u32) -> Result<BlockHash, Error> {
        let hash = self
            .client
            .call::<serde_json::Value>("getblockhash", &[height.into()])
            .map_err(NodeError::JsonRpc)?
            .as_str()
            .ok_or(Error::UnexpectedResponse(
                "getblockhash returned a non-string value".to_string(),
            ))?
            .parse::<BlockHash>()
            .map_err(|e| Error::UnexpectedResponse(e.to_string()))?;

        debug!(
            "{}: got block hash at height={} hash={}",
            Self::get_name(),
            height,
            hash
        );

        Ok(hash)
    }

    /// Check whether this [`BtcD`] has a peer with the specified [`SocketAddr`].
    ///
    /// # Errors
    ///
    /// Returns an error if the peer-info JSON-RPC call fails.
    pub fn has_peer(&self, socket: SocketAddr) -> Result<bool, Error> {
        let peers = self
            .client
            .call::<serde_json::Value>("getpeerinfo", &[])
            .map_err(NodeError::JsonRpc)?;

        let has_peer = peers.as_array().is_some_and(|v| {
            v.iter().any(|p| {
                let inbound = p["inbound"].as_bool().unwrap_or(false);
                if inbound {
                    // For inbound connections, `addr` is the peer's ephemeral port
                    // and `addrlocal` is our own listening port — neither gives us
                    // the peer's listening port, so we can't match on socket directly.
                    // Instead, match on `addrlocal` == our own socket as a proxy
                    // for confirming the connection is established.
                    p["addrlocal"]
                        .as_str()
                        .is_some_and(|a| a.contains(&self.p2p_socket.to_string()))
                } else {
                    // For outbound connections, `addr` is the peer's listening port.
                    p["addr"]
                        .as_str()
                        .is_some_and(|a| a.contains(&socket.to_string()))
                }
            })
        });

        debug!(
            "{}: checked peer connection at socket={} connected={}",
            Self::get_name(),
            socket,
            has_peer
        );

        Ok(has_peer)
    }

    /// Connect this [`BtcD`] to a peer at [`socket`](SocketAddr).
    /// Use exponential backoff for a maximum of 5 seconds while you wait for the connection.
    ///
    /// # Errors
    ///
    /// Returns an error if the add-node RPC call fails or the peer does not
    /// appear in `getpeerinfo` within the timeout.
    pub fn add_peer(&self, socket: SocketAddr) -> Result<(), Error> {
        debug!("{}: adding peer with socket={}", Self::get_name(), socket);

        self.client
            .add_node(&socket.to_string(), AddNodeCommand::Add)
            .map_err(NodeError::JsonRpc)?;

        let mut delay = CONNECTION_INTERVAL;

        let start = Instant::now();
        while start.elapsed() < CONNECTION_TIMEOUT {
            let peers = self
                .client
                .call::<serde_json::Value>("getpeerinfo", &[])
                .map_err(NodeError::JsonRpc)?;
            if peers.as_array().is_some_and(|v| {
                v.iter().any(|p| {
                    p["addr"]
                        .as_str()
                        .is_some_and(|a| a.contains(&socket.to_string()))
                })
            }) {
                debug!("{}: connected peer at socket={}", Self::get_name(), socket);
                return Ok(());
            }
            sleep(delay);
            delay = (delay * 2).min(Duration::from_secs(1));
        }

        Err(NodeError::PeerConnectionTimeout((self.get_p2p_socket(), socket)).into())
    }

    /// Return the peer count of [`BtcD`].
    ///
    /// # Errors
    ///
    /// Returns an error if the peer-info JSON-RPC call fails or returns a non-array response.
    pub fn get_peer_count(&self) -> Result<u32, Error> {
        let peers = self
            .client
            .call::<serde_json::Value>("getpeerinfo", &[])
            .map_err(NodeError::JsonRpc)?;
        let peer_count = peers
            .as_array()
            .ok_or(Error::UnexpectedResponse(
                "getpeerinfo returned a non-array value".to_string(),
            ))?
            .len() as u32;

        debug!("{}: got peer count value={}", Self::get_name(), peer_count);

        Ok(peer_count)
    }

    /// Generate `count` blocks.
    ///
    /// Returns the block hashes as a [`Vec<BlockHash>`].
    ///
    /// # Errors
    ///
    /// Returns an error if block generation fails or the response contains an invalid block hash.
    pub fn generate(&self, count: u32) -> Result<Vec<BlockHash>, Error> {
        debug!("{}: generating count={} block(s)", Self::get_name(), count);

        let hashes = self
            .client
            .call::<serde_json::Value>("generate", &[serde_json::Value::Number(count.into())])
            .map_err(NodeError::JsonRpc)?
            .as_array()
            .ok_or(Error::UnexpectedResponse(
                "generate returned a non-array value".to_string(),
            ))?
            .iter()
            .map(|h| {
                h.as_str()
                    .ok_or(Error::UnexpectedResponse(
                        "generate returned a non-string hash".to_string(),
                    ))?
                    .parse::<BlockHash>()
                    .map_err(|e| Error::UnexpectedResponse(e.to_string()))
            })
            .collect::<Result<Vec<BlockHash>, Error>>()?;
        Ok(hashes)
    }

    /// Validate typed and raw configuration.
    fn validate_configuration(conf: &BtcDConf) -> Result<(), Error> {
        const OPTIONS: &[&str] = &[
            "cfilters",
            "configfile",
            "connect",
            "datadir",
            "dnsseed",
            "generate",
            "listen",
            "logdir",
            "miningaddr",
            "nocfilters",
            "norpc",
            "notls",
            "prune",
            "regtest",
            "rpcpass",
            "rpclisten",
            "rpcuser",
            "signet",
            "simnet",
            "testnet",
            "testnet3",
            "testnet4",
            "tls",
            "txindex",
            "v2transport",
        ];
        const BOOLEAN_OPTIONS: &[&str] = &[
            "cfilters",
            "dnsseed",
            "generate",
            "listen",
            "prune",
            "regtest",
            "rpc",
            "signet",
            "simnet",
            "testnet",
            "testnet3",
            "testnet4",
            "txindex",
            "v2transport",
        ];

        validate_node_arguments(&conf.args)?;

        if conf.args.prune == PruneMode::Manual {
            return Err(NodeError::InvalidConfiguration(
                "btcd does not support manual pruning".to_string(),
            )
            .into());
        }
        if let PruneMode::Automatic(target_mib) = conf.args.prune {
            if target_mib < MIN_PRUNE_TARGET_MIB {
                return Err(NodeError::InvalidConfiguration(format!(
                    "btcd automatic pruning target must be at least {MIN_PRUNE_TARGET_MIB} MiB (got {target_mib} MiB)"
                ))
                .into());
            }
        }
        if let Some(address) = &conf.btcd_args.mining_address {
            if !address.is_valid_for_network(conf.args.network) {
                return Err(NodeError::InvalidConfiguration(format!(
                    "mining address {} is incompatible with network {}",
                    address.assume_checked_ref(),
                    conf.args.network
                ))
                .into());
            }
        }
        if let Some(arg) = find_conflicting_argument(&conf.raw_args, OPTIONS, BOOLEAN_OPTIONS) {
            return Err(NodeError::ConflictingArgument(arg).into());
        }

        Ok(())
    }

    /// Validate the configuration and create daemon arguments.
    fn configured_args(conf: &BtcDConf) -> Result<Vec<String>, Error> {
        Self::validate_configuration(conf)?;

        let mut args = Vec::new();
        match conf.args.network {
            Network::Bitcoin => {}
            Network::Testnet => args.push("--testnet".to_string()),
            Network::Testnet4 => args.push("--testnet4".to_string()),
            Network::Signet => args.push("--signet".to_string()),
            Network::Regtest => args.push("--regtest".to_string()),
        }

        args.extend(
            conf.args
                .fixed_peers
                .iter()
                .map(|peer| format!("--connect={peer}")),
        );
        if !conf.args.cbf_index {
            args.push("--nocfilters".to_string());
        }
        let prune = match conf.args.prune {
            PruneMode::Disabled => 0,
            PruneMode::Automatic(target_mib) => target_mib,
            PruneMode::Manual => unreachable!("manual pruning was rejected above"),
        };
        args.push(format!("--prune={prune}"));
        if conf.args.v2_transport {
            args.push("--v2transport".to_string());
        }
        if conf.args.txindex {
            args.push("--txindex".to_string());
        }

        // Plaintext RPC on localhost is a halfin-owned invariant.
        args.push("--notls".to_string());
        if !conf.btcd_args.dns_seed {
            args.push("--nodnsseed".to_string());
        }
        if let Some(address) = &conf.btcd_args.mining_address {
            args.push(format!("--miningaddr={}", address.assume_checked_ref()));
        }

        Ok(args)
    }

    /// Poll `getblockchaininfo` until it succeeds.
    /// Then, create and return the authenticated client.
    ///
    /// Returns `Err` if the [`Node`] is not responsive within `timeout`.
    fn wait_for_client(rpc_url: &str, auth: &Auth, timeout: Duration) -> Result<Client, Error> {
        let start = Instant::now();
        while start.elapsed() < timeout {
            if let Ok(client) = Client::new_with_auth(rpc_url, auth.clone()) {
                if client
                    .call::<serde_json::Value>("getblockchaininfo", &[])
                    .is_ok()
                {
                    return Ok(client);
                }
            }
            sleep(Duration::from_millis(200));
        }

        Err(Error::ClientSetupTimeout)
    }
}

impl Drop for BtcD {
    /// Terminate the `btcd` process and wait for it to exit.
    ///
    /// Ignore errors from `kill` and `wait` to prevent a panic in `Drop`.
    fn drop(&mut self) {
        debug!(
            "{}: killing process with pid={}",
            Self::get_name(),
            self.process.id()
        );
        let _ = self.process.kill();
        let _ = self.process.wait();
    }
}

#[cfg(all(test, halfin_node))]
mod test;
