name: Commits

on:
    push:
      branches: [ master ]
    pull_request:

permissions: {}

jobs:
    signatures:
        name: Check PGP Signatures
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Assert Commits are Signed
              shell: bash
              run: bash contrib/check-commit-signatures.sh
