name: Code Coverage

on:
    push:
        branches: [ master ]
    pull_request:

permissions: {}
env:
    CARGO_TERM_COLOR: always
    CARGO_LLVM_COV_SETUP: yes
    RUST_BACKTRACE: 1

jobs:
    llvm-cov:
        name: LLVM Cov
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false

            - name: Setup Rust Cache
              uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

            - name: Setup cargo-rbmt
              uses: ./.github/actions/setup-rbmt

            # ElectrumX needs Python 3.10 to run
            - name: Setup Python 3.10
              uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
              with:
                  python-version: '3.10'

            - name: Generate HTML Coverage Report
              shell: bash
              run: |
                  cargo rbmt run --toolchain stable -- llvm-cov \
                      --all-features \
                      --html \
                      --ignore-filename-regex '(^|/)test[.]rs$'

            - name: Generate LCOV Coverage Report
              shell: bash
              run: |
                  cargo rbmt run --toolchain stable -- llvm-cov report \
                      --lcov \
                      --output-path target/llvm-cov/lcov.info \
                      --ignore-filename-regex '(^|/)test[.]rs$'

            - name: Upload Coverage Report
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: coverage-report
                  path: |
                      target/llvm-cov/html
                      target/llvm-cov/lcov.info
                  if-no-files-found: error
